
all: sc_app sc_element sc_store sc_sup simple_cache

sc_app: 
	erlc -o ebin src/sc_app.erl

sc_element:
	erlc -o ebin src/sc_element.erl

sc_store:
	erlc -o ebin src/sc_store.erl

sc_sup:
	erlc -o ebin src/sc_sup.erl

simple_cache:
	erlc -o ebin src/simple_cache.erl